/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';

/**
 * Provides the OrderApiConfiguration configuration object with a given root URL.
 */
export function provideOrderApiConfiguration(rootUrl: string) {
  var config = new OrderApiConfiguration();
  config.rootUrl = rootUrl;
  return {
    provide: OrderApiConfiguration,
    useValue: config
  };
}

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class OrderApiConfiguration {
  rootUrl: string = 'http://localhost:8080';
}

/**
 * Parameters for `OrderApiModule.forRoot()`
 */
export interface OrderApiConfigurationParams {
  rootUrl?: string;
}
