/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { GetById$Params as GetById$Params } from './fn/product-service/get-by-id';
export { getById as getById } from './fn/product-service/get-by-id';
export type { Update$Params as Update$Params } from './fn/product-service/update';
export { update as update } from './fn/product-service/update';
export type { Delete$Params as Delete$Params } from './fn/product-service/delete';
export { delete$ as delete$ } from './fn/product-service/delete';
export type { GetAllProducts$Params as GetAllProducts$Params } from './fn/product-service/get-all-products';
export { getAllProducts as getAllProducts } from './fn/product-service/get-all-products';
export type { Create$Params as Create$Params } from './fn/product-service/create';
export { create as create } from './fn/product-service/create';
export type { RelatedProducts$Params as RelatedProducts$Params } from './fn/product-service/related-products';
export { relatedProducts as relatedProducts } from './fn/product-service/related-products';
export type { Filter$Params as Filter$Params } from './fn/product-service/filter';
export { filter as filter } from './fn/product-service/filter';
export type { GetFeaturedProducts$Params as GetFeaturedProducts$Params } from './fn/product-service/get-featured-products';
export { getFeaturedProducts as getFeaturedProducts } from './fn/product-service/get-featured-products';
export type { GetById1$Params as GetById1$Params } from './fn/category-service/get-by-id-1';
export { getById1 as getById1 } from './fn/category-service/get-by-id-1';
export type { Update1$Params as Update1$Params } from './fn/category-service/update-1';
export { update1 as update1 } from './fn/category-service/update-1';
export type { Delete1$Params as Delete1$Params } from './fn/category-service/delete-1';
export { delete1 as delete1 } from './fn/category-service/delete-1';
export type { GetAll$Params as GetAll$Params } from './fn/category-service/get-all';
export { getAll as getAll } from './fn/category-service/get-all';
export type { Create1$Params as Create1$Params } from './fn/category-service/create-1';
export { create1 as create1 } from './fn/category-service/create-1';
