/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CategoryRequestDto } from './models/category-request-dto';
export type { CategoryResponseDto } from './models/category-response-dto';
export type { CreateProductRequestDto } from './models/create-product-request-dto';
export type { PageResponseProductResponseDto } from './models/page-response-product-response-dto';
export type { ProductResponseDto } from './models/product-response-dto';
export type { UpdateProductRequestDto } from './models/update-product-request-dto';
