/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';

/**
 * Provides the ProductApiConfiguration configuration object with a given root URL.
 */
export function provideProductApiConfiguration(rootUrl: string) {
  var config = new ProductApiConfiguration();
  config.rootUrl = rootUrl;
  return {
    provide: ProductApiConfiguration,
    useValue: config
  };
}

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class ProductApiConfiguration {
  rootUrl: string = 'http://localhost:8080';
}

/**
 * Parameters for `ProductApiModule.forRoot()`
 */
export interface ProductApiConfigurationParams {
  rootUrl?: string;
}
