/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InventoryDto } from '../models/inventory-dto';
export interface PageResponseInventoryDto {
  content?: Array<InventoryDto>;
  last?: boolean;
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
