/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReviewResponseDto {
  comment?: string;
  createdAt?: string;
  id?: string;
  imageUrls?: Array<string>;
  productId?: string;
  rating?: number;
  userId?: string;
}
