/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartItemRequest } from '../../models/cart-item-request';
import { CartResponseDto } from '../../models/cart-response-dto';

export interface AddItem$Params {
      body: CartItemRequest
}

export function addItem(http: HttpClient, rootUrl: string, params: AddItem$Params, context?: HttpContext): Observable<StrictHttpResponse<CartResponseDto>> {
  const rb = new RequestBuilder(rootUrl, addItem.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartResponseDto>;
    })
  );
}

addItem.PATH = '/api/v1/cart/items';
