/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartResponseDto } from '../../models/cart-response-dto';

export interface DecrementItem$Params {
  productId: string;
}

export function decrementItem(http: HttpClient, rootUrl: string, params: DecrementItem$Params, context?: HttpContext): Observable<StrictHttpResponse<CartResponseDto>> {
  const rb = new RequestBuilder(rootUrl, decrementItem.PATH, 'patch');
  if (params) {
    rb.path('productId', params.productId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartResponseDto>;
    })
  );
}

decrementItem.PATH = '/api/v1/cart/items/{productId}/decrement';
