/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { UpdateReview$Params as UpdateReview$Params } from './fn/reviews/update-review';
export { updateReview as updateReview } from './fn/reviews/update-review';
export type { DeleteReview$Params as DeleteReview$Params } from './fn/reviews/delete-review';
export { deleteReview as deleteReview } from './fn/reviews/delete-review';
export type { CreateReview$Params as CreateReview$Params } from './fn/reviews/create-review';
export { createReview as createReview } from './fn/reviews/create-review';
export type { GetReviewsByProduct$Params as GetReviewsByProduct$Params } from './fn/reviews/get-reviews-by-product';
export { getReviewsByProduct as getReviewsByProduct } from './fn/reviews/get-reviews-by-product';
