/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ReviewRequestDto } from './models/review-request-dto';
export type { ReviewResponseDto } from './models/review-response-dto';
