/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';

/**
 * Provides the ReviewApiConfiguration configuration object with a given root URL.
 */
export function provideReviewApiConfiguration(rootUrl: string) {
  var config = new ReviewApiConfiguration();
  config.rootUrl = rootUrl;
  return {
    provide: ReviewApiConfiguration,
    useValue: config
  };
}

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class ReviewApiConfiguration {
  rootUrl: string = 'http://localhost:8080';
}

/**
 * Parameters for `ReviewApiModule.forRoot()`
 */
export interface ReviewApiConfigurationParams {
  rootUrl?: string;
}
