/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { GetInventory$Params as GetInventory$Params } from './fn/inventory-rest-controller/get-inventory';
export { getInventory as getInventory } from './fn/inventory-rest-controller/get-inventory';
export type { UpdateInventory$Params as UpdateInventory$Params } from './fn/inventory-rest-controller/update-inventory';
export { updateInventory as updateInventory } from './fn/inventory-rest-controller/update-inventory';
export type { GetAllInventory$Params as GetAllInventory$Params } from './fn/inventory-rest-controller/get-all-inventory';
export { getAllInventory as getAllInventory } from './fn/inventory-rest-controller/get-all-inventory';
export type { AddInventory$Params as AddInventory$Params } from './fn/inventory-rest-controller/add-inventory';
export { addInventory as addInventory } from './fn/inventory-rest-controller/add-inventory';
