/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';

/**
 * Provides the InventoryApiConfiguration configuration object with a given root URL.
 */
export function provideInventoryApiConfiguration(rootUrl: string) {
  var config = new InventoryApiConfiguration();
  config.rootUrl = rootUrl;
  return {
    provide: InventoryApiConfiguration,
    useValue: config
  };
}

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class InventoryApiConfiguration {
  rootUrl: string = 'http://localhost:8080';
}

/**
 * Parameters for `InventoryApiModule.forRoot()`
 */
export interface InventoryApiConfigurationParams {
  rootUrl?: string;
}
