/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { InventoryDto } from './models/inventory-dto';
export type { PageResponseInventoryDto } from './models/page-response-inventory-dto';
