/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { GetSwagger$Params as GetSwagger$Params } from './fn/swagger-aggregator-rest-controller/get-swagger';
export { getSwagger as getSwagger } from './fn/swagger-aggregator-rest-controller/get-swagger';
