/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';

/**
 * Provides the CartApiConfiguration configuration object with a given root URL.
 */
export function provideCartApiConfiguration(rootUrl: string) {
  var config = new CartApiConfiguration();
  config.rootUrl = rootUrl;
  return {
    provide: CartApiConfiguration,
    useValue: config
  };
}

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class CartApiConfiguration {
  rootUrl: string = 'http://localhost:8080';
}

/**
 * Parameters for `CartApiModule.forRoot()`
 */
export interface CartApiConfigurationParams {
  rootUrl?: string;
}
