/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaymentResponse } from '../models/payment-response';
export interface PageResponsePaymentResponse {
  content?: Array<PaymentResponse>;
  last?: boolean;
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
