/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentCreateResponse {
  amount?: number;
  currency?: string;
  key?: string;
  razorpayOrderId?: string;
}
