/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategoryResponseDto {
  createdAt?: string;
  description?: string;
  id?: string;
  name?: string;
  updatedAt?: string;
}
