/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateProductRequestDto {
  brand: string;
  categoryId: string;
  description?: string;
  featured: boolean;
  name: string;
  price: number;
  productSize?: 'XS' | 'S' | 'M' | 'L' | 'XL' | 'XXL';
  sku: string;
}
