/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateProductRequestDto {
  categoryId: string;
  description?: string;
  name: string;
  price: number;
  sku: string;
}
