/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProductResponseDto } from '../models/product-response-dto';
export interface PageResponseProductResponseDto {
  content?: Array<ProductResponseDto>;
  last?: boolean;
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
