/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductResponseDto {
  categoryId?: string;
  categoryName?: string;
  createdAt?: string;
  description?: string;
  id?: string;
  name?: string;
  price?: number;
  sku?: string;
  status?: string;
  updatedAt?: string;
}
