/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductResponseDto {
  brand?: string;
  categoryId?: string;
  categoryName?: string;
  createdAt?: string;
  description?: string;
  featured?: boolean;
  id?: string;
  imageUrls?: Array<string>;
  name?: string;
  price?: number;
  productColor?: 'RED' | 'BLUE' | 'GREEN' | 'BLACK' | 'WHITE' | 'GREY' | 'YELLOW' | 'ORANGE';
  size?: 'XS' | 'S' | 'M' | 'L' | 'XL' | 'XXL';
  sku?: string;
  status?: 'ACTIVE' | 'INACTIVE' | 'OUT_OF_STOCK';
  updatedAt?: string;
}
