/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserResponseDto } from '../models/user-response-dto';
export interface PageResponseUserResponseDto {
  content?: Array<UserResponseDto>;
  last?: boolean;
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
