/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponseDto {
  addressCity?: string;
  addressCountry?: string;
  addressStreet?: string;
  addressZipCode?: string;
  countryCode?: string;
  createdAt?: string;
  email?: string;
  firstName?: string;
  id?: string;
  lastName?: string;
  lastSeen?: string;
  phoneNumber?: string;
  roles?: Array<'USER' | 'ADMIN' | 'SELLER' | 'SUPPORT'>;
  updatedAt?: string;
}
