/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';

/**
 * Provides the AuthApiConfiguration configuration object with a given root URL.
 */
export function provideAuthApiConfiguration(rootUrl: string) {
  var config = new AuthApiConfiguration();
  config.rootUrl = rootUrl;
  return {
    provide: AuthApiConfiguration,
    useValue: config
  };
}

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class AuthApiConfiguration {
  rootUrl: string = 'http://localhost:8080';
}

/**
 * Parameters for `AuthApiModule.forRoot()`
 */
export interface AuthApiConfigurationParams {
  rootUrl?: string;
}
