/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderItemDto } from '../models/order-item-dto';
export interface OrderResponseDto {
  customerId?: string;
  items?: Array<OrderItemDto>;
  orderId?: string;
  status?: 'CREATED' | 'CONFIRMED' | 'CANCELLED' | 'FAILED' | 'STOCK_RESERVED' | 'STOCK_FAILED';
}
