/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderResponseDto } from '../models/order-response-dto';
export interface PageResponseOrderResponseDto {
  content?: Array<OrderResponseDto>;
  last?: boolean;
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
