/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InventoryDto } from '../../models/inventory-dto';

export interface AddInventory$Params {
      body: InventoryDto
}

export function addInventory(http: HttpClient, rootUrl: string, params: AddInventory$Params, context?: HttpContext): Observable<StrictHttpResponse<InventoryDto>> {
  const rb = new RequestBuilder(rootUrl, addInventory.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InventoryDto>;
    })
  );
}

addInventory.PATH = '/api/v1/inventory';
