/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InventoryDto } from '../../models/inventory-dto';

export interface GetInventory$Params {
  productId: string;
}

export function getInventory(http: HttpClient, rootUrl: string, params: GetInventory$Params, context?: HttpContext): Observable<StrictHttpResponse<InventoryDto>> {
  const rb = new RequestBuilder(rootUrl, getInventory.PATH, 'get');
  if (params) {
    rb.path('productId', params.productId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InventoryDto>;
    })
  );
}

getInventory.PATH = '/api/v1/inventory/{productId}';
