/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';

/**
 * Provides the PaymentApiConfiguration configuration object with a given root URL.
 */
export function providePaymentApiConfiguration(rootUrl: string) {
  var config = new PaymentApiConfiguration();
  config.rootUrl = rootUrl;
  return {
    provide: PaymentApiConfiguration,
    useValue: config
  };
}

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class PaymentApiConfiguration {
  rootUrl: string = 'http://localhost:8080';
}

/**
 * Parameters for `PaymentApiModule.forRoot()`
 */
export interface PaymentApiConfigurationParams {
  rootUrl?: string;
}
