/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CartItemDto } from '../models/cart-item-dto';
export interface CartResponseDto {
  items?: Array<CartItemDto>;
  totalAmount?: number;
  userId?: string;
}
