/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CartItemDto {
  imageUrl?: string;
  name?: string;
  productId?: string;
  quantity?: number;
  subTotal?: number;
  unitPrice?: number;
}
