/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';

/**
 * Provides the UserApiConfiguration configuration object with a given root URL.
 */
export function provideUserApiConfiguration(rootUrl: string) {
  var config = new UserApiConfiguration();
  config.rootUrl = rootUrl;
  return {
    provide: UserApiConfiguration,
    useValue: config
  };
}

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class UserApiConfiguration {
  rootUrl: string = 'http://localhost:8080';
}

/**
 * Parameters for `UserApiModule.forRoot()`
 */
export interface UserApiConfigurationParams {
  rootUrl?: string;
}
