/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReviewRequestDto } from '../../models/review-request-dto';
import { ReviewResponseDto } from '../../models/review-response-dto';

export interface CreateReview$Params {
      body?: {
'review': ReviewRequestDto;
'files': Array<Blob>;
}
}

export function createReview(http: HttpClient, rootUrl: string, params?: CreateReview$Params, context?: HttpContext): Observable<StrictHttpResponse<ReviewResponseDto>> {
  const rb = new RequestBuilder(rootUrl, createReview.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReviewResponseDto>;
    })
  );
}

createReview.PATH = '/api/v1/reviews';
