/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AccessTokenResponseDto {
  accessToken?: string;
  expiresIn?: number;
  issuedAt?: string;
  roles?: Array<string>;
  tokenType?: string;
  username?: string;
}
