/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthenticationResponseDto {
  access_token?: string;
  expires_in?: number;
  issued_at?: string;
  refresh_token?: string;
  roles?: Array<string>;
  token_type?: string;
  username?: string;
}
